---
title: "Assignment 4"
author: "Kyle Pinca"
date: "11/9/2021"
output: html_document

## 1
```{r}
House=read.csv("kc house sales.csv")
House$date=as.Date(House$date,format="%Y%m%d")
House$view=as.factor(House$view)
House$waterfront=as.factor(House$waterfront)
House$zipcode=as.factor(House$zipcode)
House[15871,3]=3
attach(House)
library(ISLR2)
library(MASS)
library(class)
library(ROCR)
```

## 2
```{r}
glm.fit=glm(log(price)~.-sqft_basement, House, family=gaussian)
```

## 3
```{r}
library(boot)
set.seed(100)
cv.err=cv.glm(House, glmfit= glm.fit, K=10)
names(cv.err)
cv.err$delta

```


## 4
```{r}
house.fit=glm(log(price)~(.-sqft_basement-zipcode)^2+zipcode, House, family=gaussian)
```

## 5
```{r}
set.seed(100)
cv.err2=cv.glm(House, glmfit = house.fit, K=10)
names(cv.err2)
cv.err2$delta

```

## 6
```{r}

```

## 7
```{r}
Bank = read.csv("bank marketing.csv")
Bank$y=as.factor(Bank$y)
attach(Bank)
```

## 8
```{r}
bank.fit = glm(y~. -duration,data=Bank,family=binomial)
```
## 9
```{r}

```
